#!/usr/bin/env python3
"""Generate INDEX.md from all prompt cards under prompts/.

Run from repo root:

    python scripts/build_index.py

Reads frontmatter from every prompts/*/*.md file and emits a catalog grouped
by direction and a tag matrix. Run validate.py first; this script trusts
that frontmatter is well-formed.
"""
from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
PROMPTS_DIR = REPO_ROOT / "prompts"
INDEX_PATH = REPO_ROOT / "INDEX.md"

DIRECTION_ORDER = ["rag", "agent", "rlhf", "sft", "multimodal", "cot", "eval"]
DIRECTION_LABEL = {
    "rag": "RAG",
    "agent": "Agent",
    "rlhf": "RLHF",
    "sft": "SFT",
    "multimodal": "Multimodal",
    "cot": "Chain-of-Thought",
    "eval": "Evaluation",
}


def parse_frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{path}: missing frontmatter")
    rest = text[4:]
    end = rest.find("\n---\n")
    if end == -1:
        raise ValueError(f"{path}: unterminated frontmatter")
    fm = yaml.safe_load(rest[:end])
    if not isinstance(fm, dict):
        raise ValueError(f"{path}: frontmatter is not a mapping")
    return fm


def main() -> int:
    cards = sorted(PROMPTS_DIR.glob("*/*.md"))
    if not cards:
        print(f"ERROR: no prompt cards found under {PROMPTS_DIR}", file=sys.stderr)
        return 1

    by_dir: dict[str, list[tuple[dict, str]]] = defaultdict(list)
    by_tag: dict[str, list[tuple[dict, str]]] = defaultdict(list)

    for path in cards:
        fm = parse_frontmatter(path)
        rel = path.relative_to(REPO_ROOT).as_posix()
        by_dir[fm["direction"]].append((fm, rel))
        for tag in fm.get("tags", []):
            by_tag[tag].append((fm, rel))

    lines: list[str] = []
    lines.append("# prompt-atlas Index")
    lines.append("")
    lines.append("> Auto-generated by `scripts/build_index.py`. Do not edit by hand.")
    lines.append("")
    lines.append(f"**Total cards:** {len(cards)}")
    lines.append("")
    lines.append("## Cards by direction")
    lines.append("")

    for direction in DIRECTION_ORDER:
        items = by_dir.get(direction)
        if not items:
            continue
        lines.append(f"### {DIRECTION_LABEL[direction]} (`{direction}`)")
        lines.append("")
        lines.append("| Card | Status | Tags | Audience |")
        lines.append("|------|--------|------|----------|")
        for fm, rel in sorted(items, key=lambda pair: pair[0]["id"]):
            link = f"[{fm['title']}]({rel})"
            tags = ", ".join(f"`{t}`" for t in fm["tags"])
            audience = ", ".join(f"`{a}`" for a in fm["audience"])
            lines.append(
                f"| {link} | `{fm['status']}` | {tags} | {audience} |"
            )
        lines.append("")

    lines.append("## Cards by tag")
    lines.append("")
    for tag in sorted(by_tag):
        items = sorted(by_tag[tag], key=lambda pair: pair[0]["id"])
        items_str = ", ".join(f"[{fm['title']}]({rel})" for fm, rel in items)
        lines.append(f"- **`{tag}`** — {items_str}")
    lines.append("")

    INDEX_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"OK: wrote {INDEX_PATH.relative_to(REPO_ROOT).as_posix()} with {len(cards)} card(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
